/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 15
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 62
#define ALIAS_COUNT 0
#define TOKEN_COUNT 56
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_module = 2,
  anon_sym_import = 3,
  anon_sym_use = 4,
  anon_sym_export = 5,
  anon_sym_external = 6,
  anon_sym_fn = 7,
  anon_sym_type = 8,
  anon_sym_effect = 9,
  anon_sym_alias = 10,
  anon_sym_let = 11,
  anon_sym_const = 12,
  anon_sym_mut = 13,
  anon_sym_consume = 14,
  anon_sym_readonly = 15,
  anon_sym_if = 16,
  anon_sym_else = 17,
  anon_sym_match = 18,
  anon_sym_for = 19,
  anon_sym_while = 20,
  anon_sym_loop = 21,
  anon_sym_in = 22,
  anon_sym_return = 23,
  anon_sym_break = 24,
  anon_sym_continue = 25,
  anon_sym_test = 26,
  anon_sym_true = 27,
  anon_sym_false = 28,
  anon_sym_with = 29,
  anon_sym_throw = 30,
  anon_sym_as = 31,
  anon_sym_is = 32,
  anon_sym_spawn = 33,
  anon_sym_supervised = 34,
  anon_sym_parallel = 35,
  anon_sym_detach = 36,
  anon_sym_blocking = 37,
  anon_sym_protocol = 38,
  anon_sym_interrupt = 39,
  anon_sym_forbid = 40,
  anon_sym_realtime = 41,
  anon_sym_defer = 42,
  anon_sym_errdefer = 43,
  anon_sym_select = 44,
  anon_sym_lemma = 45,
  sym_number_literal = 46,
  anon_sym_DQUOTE = 47,
  aux_sym_string_literal_token1 = 48,
  aux_sym_string_literal_token2 = 49,
  anon_sym_DOLLAR_LBRACE = 50,
  aux_sym_string_literal_token3 = 51,
  anon_sym_RBRACE = 52,
  sym_line_comment = 53,
  sym_doc_comment = 54,
  sym_block_comment = 55,
  sym_source_file = 56,
  sym__top_level = 57,
  sym__declaration_placeholder = 58,
  sym_string_literal = 59,
  aux_sym_source_file_repeat1 = 60,
  aux_sym_string_literal_repeat1 = 61,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_module] = "keyword",
  [anon_sym_import] = "keyword",
  [anon_sym_use] = "keyword",
  [anon_sym_export] = "keyword",
  [anon_sym_external] = "keyword",
  [anon_sym_fn] = "keyword",
  [anon_sym_type] = "keyword",
  [anon_sym_effect] = "keyword",
  [anon_sym_alias] = "keyword",
  [anon_sym_let] = "keyword",
  [anon_sym_const] = "keyword",
  [anon_sym_mut] = "keyword",
  [anon_sym_consume] = "keyword",
  [anon_sym_readonly] = "keyword",
  [anon_sym_if] = "keyword",
  [anon_sym_else] = "keyword",
  [anon_sym_match] = "keyword",
  [anon_sym_for] = "keyword",
  [anon_sym_while] = "keyword",
  [anon_sym_loop] = "keyword",
  [anon_sym_in] = "keyword",
  [anon_sym_return] = "keyword",
  [anon_sym_break] = "keyword",
  [anon_sym_continue] = "keyword",
  [anon_sym_test] = "keyword",
  [anon_sym_true] = "keyword",
  [anon_sym_false] = "keyword",
  [anon_sym_with] = "keyword",
  [anon_sym_throw] = "keyword",
  [anon_sym_as] = "keyword",
  [anon_sym_is] = "keyword",
  [anon_sym_spawn] = "keyword",
  [anon_sym_supervised] = "keyword",
  [anon_sym_parallel] = "keyword",
  [anon_sym_detach] = "keyword",
  [anon_sym_blocking] = "keyword",
  [anon_sym_protocol] = "keyword",
  [anon_sym_interrupt] = "keyword",
  [anon_sym_forbid] = "keyword",
  [anon_sym_realtime] = "keyword",
  [anon_sym_defer] = "keyword",
  [anon_sym_errdefer] = "keyword",
  [anon_sym_select] = "keyword",
  [anon_sym_lemma] = "keyword",
  [sym_number_literal] = "number_literal",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [aux_sym_string_literal_token2] = "string_literal_token2",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [aux_sym_string_literal_token3] = "string_literal_token3",
  [anon_sym_RBRACE] = "}",
  [sym_line_comment] = "line_comment",
  [sym_doc_comment] = "doc_comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym__top_level] = "_top_level",
  [sym__declaration_placeholder] = "_declaration_placeholder",
  [sym_string_literal] = "string_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_module] = anon_sym_module,
  [anon_sym_import] = anon_sym_module,
  [anon_sym_use] = anon_sym_module,
  [anon_sym_export] = anon_sym_module,
  [anon_sym_external] = anon_sym_module,
  [anon_sym_fn] = anon_sym_module,
  [anon_sym_type] = anon_sym_module,
  [anon_sym_effect] = anon_sym_module,
  [anon_sym_alias] = anon_sym_module,
  [anon_sym_let] = anon_sym_module,
  [anon_sym_const] = anon_sym_module,
  [anon_sym_mut] = anon_sym_module,
  [anon_sym_consume] = anon_sym_module,
  [anon_sym_readonly] = anon_sym_module,
  [anon_sym_if] = anon_sym_module,
  [anon_sym_else] = anon_sym_module,
  [anon_sym_match] = anon_sym_module,
  [anon_sym_for] = anon_sym_module,
  [anon_sym_while] = anon_sym_module,
  [anon_sym_loop] = anon_sym_module,
  [anon_sym_in] = anon_sym_module,
  [anon_sym_return] = anon_sym_module,
  [anon_sym_break] = anon_sym_module,
  [anon_sym_continue] = anon_sym_module,
  [anon_sym_test] = anon_sym_module,
  [anon_sym_true] = anon_sym_module,
  [anon_sym_false] = anon_sym_module,
  [anon_sym_with] = anon_sym_module,
  [anon_sym_throw] = anon_sym_module,
  [anon_sym_as] = anon_sym_module,
  [anon_sym_is] = anon_sym_module,
  [anon_sym_spawn] = anon_sym_module,
  [anon_sym_supervised] = anon_sym_module,
  [anon_sym_parallel] = anon_sym_module,
  [anon_sym_detach] = anon_sym_module,
  [anon_sym_blocking] = anon_sym_module,
  [anon_sym_protocol] = anon_sym_module,
  [anon_sym_interrupt] = anon_sym_module,
  [anon_sym_forbid] = anon_sym_module,
  [anon_sym_realtime] = anon_sym_module,
  [anon_sym_defer] = anon_sym_module,
  [anon_sym_errdefer] = anon_sym_module,
  [anon_sym_select] = anon_sym_module,
  [anon_sym_lemma] = anon_sym_module,
  [sym_number_literal] = sym_number_literal,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [aux_sym_string_literal_token2] = aux_sym_string_literal_token2,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [aux_sym_string_literal_token3] = aux_sym_string_literal_token3,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_line_comment] = sym_line_comment,
  [sym_doc_comment] = sym_doc_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym__top_level] = sym__top_level,
  [sym__declaration_placeholder] = sym__declaration_placeholder,
  [sym_string_literal] = sym_string_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_export] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_external] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_effect] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_alias] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_mut] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_consume] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_readonly] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_match] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_loop] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_break] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_continue] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_test] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_with] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_throw] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_is] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_spawn] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_supervised] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_parallel] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_detach] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_blocking] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_protocol] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_interrupt] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_forbid] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_realtime] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_defer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_errdefer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_select] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_lemma] = {
    .visible = true,
    .named = true,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_doc_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__top_level] = {
    .visible = false,
    .named = true,
  },
  [sym__declaration_placeholder] = {
    .visible = false,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '$') ADVANCE(5);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == '0') ADVANCE(15);
      if (lookahead == '\\') ADVANCE(12);
      if (lookahead == '}') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '$') ADVANCE(5);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(37);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '{') ADVANCE(27);
      END_STATE();
    case 6:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 7:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(18);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(19);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 12:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == 'b') ADVANCE(7);
      if (lookahead == 'o') ADVANCE(8);
      if (lookahead == 'x') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '.') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '7') ||
          lookahead == '_') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(37);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '/') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\') ADVANCE(23);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_string_literal_token3);
      if (lookahead == '*') ADVANCE(30);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(35);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_string_literal_token3);
      if (lookahead == '*') ADVANCE(29);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead == '}') ADVANCE(4);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_string_literal_token3);
      if (lookahead == '*') ADVANCE(29);
      if (lookahead == '}') ADVANCE(4);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_string_literal_token3);
      if (lookahead == '/') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(35);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_string_literal_token3);
      if (lookahead == '/') ADVANCE(33);
      if (lookahead == '}') ADVANCE(38);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(35);
      if (lookahead != 0) ADVANCE(34);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_string_literal_token3);
      if (lookahead == '}') ADVANCE(39);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(35);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_string_literal_token3);
      if (lookahead == '}') ADVANCE(38);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(35);
      if (lookahead != 0) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_string_literal_token3);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '/') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_doc_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'e', 5,
        'f', 6,
        'i', 7,
        'l', 8,
        'm', 9,
        'p', 10,
        'r', 11,
        's', 12,
        't', 13,
        'u', 14,
        'w', 15,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(16);
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 2:
      if (lookahead == 'l') ADVANCE(18);
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == 'f') ADVANCE(22);
      if (lookahead == 'l') ADVANCE(23);
      if (lookahead == 'r') ADVANCE(24);
      if (lookahead == 'x') ADVANCE(25);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(26);
      if (lookahead == 'n') ADVANCE(27);
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 7:
      if (lookahead == 'f') ADVANCE(29);
      if (lookahead == 'm') ADVANCE(30);
      if (lookahead == 'n') ADVANCE(31);
      if (lookahead == 's') ADVANCE(32);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(33);
      if (lookahead == 'o') ADVANCE(34);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(35);
      if (lookahead == 'o') ADVANCE(36);
      if (lookahead == 'u') ADVANCE(37);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(38);
      if (lookahead == 'r') ADVANCE(39);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(41);
      if (lookahead == 'p') ADVANCE(42);
      if (lookahead == 'u') ADVANCE(43);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(44);
      if (lookahead == 'h') ADVANCE(45);
      if (lookahead == 'r') ADVANCE(46);
      if (lookahead == 'y') ADVANCE(47);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(48);
      END_STATE();
    case 15:
      if (lookahead == 'h') ADVANCE(49);
      if (lookahead == 'i') ADVANCE(50);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(51);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(52);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 21:
      if (lookahead == 'f') ADVANCE(55);
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 22:
      if (lookahead == 'f') ADVANCE(57);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(58);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(59);
      END_STATE();
    case 25:
      if (lookahead == 'p') ADVANCE(60);
      if (lookahead == 't') ADVANCE(61);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(62);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(63);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 30:
      if (lookahead == 'p') ADVANCE(64);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_in);
      if (lookahead == 't') ADVANCE(65);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_is);
      END_STATE();
    case 33:
      if (lookahead == 'm') ADVANCE(66);
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 34:
      if (lookahead == 'o') ADVANCE(68);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(69);
      END_STATE();
    case 36:
      if (lookahead == 'd') ADVANCE(70);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(71);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(72);
      END_STATE();
    case 39:
      if (lookahead == 'o') ADVANCE(73);
      END_STATE();
    case 40:
      if (lookahead == 'a') ADVANCE(74);
      if (lookahead == 't') ADVANCE(75);
      END_STATE();
    case 41:
      if (lookahead == 'l') ADVANCE(76);
      END_STATE();
    case 42:
      if (lookahead == 'a') ADVANCE(77);
      END_STATE();
    case 43:
      if (lookahead == 'p') ADVANCE(78);
      END_STATE();
    case 44:
      if (lookahead == 's') ADVANCE(79);
      END_STATE();
    case 45:
      if (lookahead == 'r') ADVANCE(80);
      END_STATE();
    case 46:
      if (lookahead == 'u') ADVANCE(81);
      END_STATE();
    case 47:
      if (lookahead == 'p') ADVANCE(82);
      END_STATE();
    case 48:
      if (lookahead == 'e') ADVANCE(83);
      END_STATE();
    case 49:
      if (lookahead == 'i') ADVANCE(84);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(85);
      END_STATE();
    case 51:
      if (lookahead == 'a') ADVANCE(86);
      END_STATE();
    case 52:
      if (lookahead == 'c') ADVANCE(87);
      END_STATE();
    case 53:
      if (lookahead == 'a') ADVANCE(88);
      END_STATE();
    case 54:
      if (lookahead == 's') ADVANCE(89);
      if (lookahead == 't') ADVANCE(90);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(91);
      END_STATE();
    case 56:
      if (lookahead == 'a') ADVANCE(92);
      END_STATE();
    case 57:
      if (lookahead == 'e') ADVANCE(93);
      END_STATE();
    case 58:
      if (lookahead == 'e') ADVANCE(94);
      END_STATE();
    case 59:
      if (lookahead == 'd') ADVANCE(95);
      END_STATE();
    case 60:
      if (lookahead == 'o') ADVANCE(96);
      END_STATE();
    case 61:
      if (lookahead == 'e') ADVANCE(97);
      END_STATE();
    case 62:
      if (lookahead == 's') ADVANCE(98);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_for);
      if (lookahead == 'b') ADVANCE(99);
      END_STATE();
    case 64:
      if (lookahead == 'o') ADVANCE(100);
      END_STATE();
    case 65:
      if (lookahead == 'e') ADVANCE(101);
      END_STATE();
    case 66:
      if (lookahead == 'm') ADVANCE(102);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 68:
      if (lookahead == 'p') ADVANCE(103);
      END_STATE();
    case 69:
      if (lookahead == 'c') ADVANCE(104);
      END_STATE();
    case 70:
      if (lookahead == 'u') ADVANCE(105);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_mut);
      END_STATE();
    case 72:
      if (lookahead == 'a') ADVANCE(106);
      END_STATE();
    case 73:
      if (lookahead == 't') ADVANCE(107);
      END_STATE();
    case 74:
      if (lookahead == 'd') ADVANCE(108);
      if (lookahead == 'l') ADVANCE(109);
      END_STATE();
    case 75:
      if (lookahead == 'u') ADVANCE(110);
      END_STATE();
    case 76:
      if (lookahead == 'e') ADVANCE(111);
      END_STATE();
    case 77:
      if (lookahead == 'w') ADVANCE(112);
      END_STATE();
    case 78:
      if (lookahead == 'e') ADVANCE(113);
      END_STATE();
    case 79:
      if (lookahead == 't') ADVANCE(114);
      END_STATE();
    case 80:
      if (lookahead == 'o') ADVANCE(115);
      END_STATE();
    case 81:
      if (lookahead == 'e') ADVANCE(116);
      END_STATE();
    case 82:
      if (lookahead == 'e') ADVANCE(117);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 84:
      if (lookahead == 'l') ADVANCE(118);
      END_STATE();
    case 85:
      if (lookahead == 'h') ADVANCE(119);
      END_STATE();
    case 86:
      if (lookahead == 's') ADVANCE(120);
      END_STATE();
    case 87:
      if (lookahead == 'k') ADVANCE(121);
      END_STATE();
    case 88:
      if (lookahead == 'k') ADVANCE(122);
      END_STATE();
    case 89:
      if (lookahead == 't') ADVANCE(123);
      if (lookahead == 'u') ADVANCE(124);
      END_STATE();
    case 90:
      if (lookahead == 'i') ADVANCE(125);
      END_STATE();
    case 91:
      if (lookahead == 'r') ADVANCE(126);
      END_STATE();
    case 92:
      if (lookahead == 'c') ADVANCE(127);
      END_STATE();
    case 93:
      if (lookahead == 'c') ADVANCE(128);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 95:
      if (lookahead == 'e') ADVANCE(129);
      END_STATE();
    case 96:
      if (lookahead == 'r') ADVANCE(130);
      END_STATE();
    case 97:
      if (lookahead == 'r') ADVANCE(131);
      END_STATE();
    case 98:
      if (lookahead == 'e') ADVANCE(132);
      END_STATE();
    case 99:
      if (lookahead == 'i') ADVANCE(133);
      END_STATE();
    case 100:
      if (lookahead == 'r') ADVANCE(134);
      END_STATE();
    case 101:
      if (lookahead == 'r') ADVANCE(135);
      END_STATE();
    case 102:
      if (lookahead == 'a') ADVANCE(136);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_loop);
      END_STATE();
    case 104:
      if (lookahead == 'h') ADVANCE(137);
      END_STATE();
    case 105:
      if (lookahead == 'l') ADVANCE(138);
      END_STATE();
    case 106:
      if (lookahead == 'l') ADVANCE(139);
      END_STATE();
    case 107:
      if (lookahead == 'o') ADVANCE(140);
      END_STATE();
    case 108:
      if (lookahead == 'o') ADVANCE(141);
      END_STATE();
    case 109:
      if (lookahead == 't') ADVANCE(142);
      END_STATE();
    case 110:
      if (lookahead == 'r') ADVANCE(143);
      END_STATE();
    case 111:
      if (lookahead == 'c') ADVANCE(144);
      END_STATE();
    case 112:
      if (lookahead == 'n') ADVANCE(145);
      END_STATE();
    case 113:
      if (lookahead == 'r') ADVANCE(146);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_test);
      END_STATE();
    case 115:
      if (lookahead == 'w') ADVANCE(147);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 118:
      if (lookahead == 'e') ADVANCE(148);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_with);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_alias);
      END_STATE();
    case 121:
      if (lookahead == 'i') ADVANCE(149);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_break);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 124:
      if (lookahead == 'm') ADVANCE(150);
      END_STATE();
    case 125:
      if (lookahead == 'n') ADVANCE(151);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_defer);
      END_STATE();
    case 127:
      if (lookahead == 'h') ADVANCE(152);
      END_STATE();
    case 128:
      if (lookahead == 't') ADVANCE(153);
      END_STATE();
    case 129:
      if (lookahead == 'f') ADVANCE(154);
      END_STATE();
    case 130:
      if (lookahead == 't') ADVANCE(155);
      END_STATE();
    case 131:
      if (lookahead == 'n') ADVANCE(156);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 133:
      if (lookahead == 'd') ADVANCE(157);
      END_STATE();
    case 134:
      if (lookahead == 't') ADVANCE(158);
      END_STATE();
    case 135:
      if (lookahead == 'r') ADVANCE(159);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(anon_sym_lemma);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(anon_sym_match);
      END_STATE();
    case 138:
      if (lookahead == 'e') ADVANCE(160);
      END_STATE();
    case 139:
      if (lookahead == 'l') ADVANCE(161);
      END_STATE();
    case 140:
      if (lookahead == 'c') ADVANCE(162);
      END_STATE();
    case 141:
      if (lookahead == 'n') ADVANCE(163);
      END_STATE();
    case 142:
      if (lookahead == 'i') ADVANCE(164);
      END_STATE();
    case 143:
      if (lookahead == 'n') ADVANCE(165);
      END_STATE();
    case 144:
      if (lookahead == 't') ADVANCE(166);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(anon_sym_spawn);
      END_STATE();
    case 146:
      if (lookahead == 'v') ADVANCE(167);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(anon_sym_throw);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 149:
      if (lookahead == 'n') ADVANCE(168);
      END_STATE();
    case 150:
      if (lookahead == 'e') ADVANCE(169);
      END_STATE();
    case 151:
      if (lookahead == 'u') ADVANCE(170);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(anon_sym_detach);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(anon_sym_effect);
      END_STATE();
    case 154:
      if (lookahead == 'e') ADVANCE(171);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(anon_sym_export);
      END_STATE();
    case 156:
      if (lookahead == 'a') ADVANCE(172);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(anon_sym_forbid);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 159:
      if (lookahead == 'u') ADVANCE(173);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 161:
      if (lookahead == 'e') ADVANCE(174);
      END_STATE();
    case 162:
      if (lookahead == 'o') ADVANCE(175);
      END_STATE();
    case 163:
      if (lookahead == 'l') ADVANCE(176);
      END_STATE();
    case 164:
      if (lookahead == 'm') ADVANCE(177);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(anon_sym_select);
      END_STATE();
    case 167:
      if (lookahead == 'i') ADVANCE(178);
      END_STATE();
    case 168:
      if (lookahead == 'g') ADVANCE(179);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(anon_sym_consume);
      END_STATE();
    case 170:
      if (lookahead == 'e') ADVANCE(180);
      END_STATE();
    case 171:
      if (lookahead == 'r') ADVANCE(181);
      END_STATE();
    case 172:
      if (lookahead == 'l') ADVANCE(182);
      END_STATE();
    case 173:
      if (lookahead == 'p') ADVANCE(183);
      END_STATE();
    case 174:
      if (lookahead == 'l') ADVANCE(184);
      END_STATE();
    case 175:
      if (lookahead == 'l') ADVANCE(185);
      END_STATE();
    case 176:
      if (lookahead == 'y') ADVANCE(186);
      END_STATE();
    case 177:
      if (lookahead == 'e') ADVANCE(187);
      END_STATE();
    case 178:
      if (lookahead == 's') ADVANCE(188);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(anon_sym_blocking);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(anon_sym_continue);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(anon_sym_errdefer);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(anon_sym_external);
      END_STATE();
    case 183:
      if (lookahead == 't') ADVANCE(189);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(anon_sym_parallel);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(anon_sym_protocol);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(anon_sym_readonly);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(anon_sym_realtime);
      END_STATE();
    case 188:
      if (lookahead == 'e') ADVANCE(190);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(anon_sym_interrupt);
      END_STATE();
    case 190:
      if (lookahead == 'd') ADVANCE(191);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(anon_sym_supervised);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 31},
  [14] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_module] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_export] = ACTIONS(1),
    [anon_sym_external] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_effect] = ACTIONS(1),
    [anon_sym_alias] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_mut] = ACTIONS(1),
    [anon_sym_consume] = ACTIONS(1),
    [anon_sym_readonly] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_match] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_loop] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_break] = ACTIONS(1),
    [anon_sym_continue] = ACTIONS(1),
    [anon_sym_test] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_with] = ACTIONS(1),
    [anon_sym_throw] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_is] = ACTIONS(1),
    [anon_sym_spawn] = ACTIONS(1),
    [anon_sym_supervised] = ACTIONS(1),
    [anon_sym_parallel] = ACTIONS(1),
    [anon_sym_detach] = ACTIONS(1),
    [anon_sym_blocking] = ACTIONS(1),
    [anon_sym_protocol] = ACTIONS(1),
    [anon_sym_interrupt] = ACTIONS(1),
    [anon_sym_forbid] = ACTIONS(1),
    [anon_sym_realtime] = ACTIONS(1),
    [anon_sym_defer] = ACTIONS(1),
    [anon_sym_errdefer] = ACTIONS(1),
    [anon_sym_select] = ACTIONS(1),
    [anon_sym_lemma] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_string_literal_token2] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_comment] = ACTIONS(5),
    [sym_block_comment] = ACTIONS(5),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(12),
    [sym__top_level] = STATE(2),
    [sym__declaration_placeholder] = STATE(2),
    [sym_string_literal] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_module] = ACTIONS(9),
    [anon_sym_import] = ACTIONS(9),
    [anon_sym_use] = ACTIONS(9),
    [anon_sym_export] = ACTIONS(9),
    [anon_sym_external] = ACTIONS(9),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_type] = ACTIONS(9),
    [anon_sym_effect] = ACTIONS(9),
    [anon_sym_alias] = ACTIONS(9),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_const] = ACTIONS(9),
    [anon_sym_mut] = ACTIONS(9),
    [anon_sym_consume] = ACTIONS(9),
    [anon_sym_readonly] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_else] = ACTIONS(9),
    [anon_sym_match] = ACTIONS(9),
    [anon_sym_for] = ACTIONS(11),
    [anon_sym_while] = ACTIONS(9),
    [anon_sym_loop] = ACTIONS(9),
    [anon_sym_in] = ACTIONS(11),
    [anon_sym_return] = ACTIONS(9),
    [anon_sym_break] = ACTIONS(9),
    [anon_sym_continue] = ACTIONS(9),
    [anon_sym_test] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [anon_sym_with] = ACTIONS(9),
    [anon_sym_throw] = ACTIONS(9),
    [anon_sym_as] = ACTIONS(9),
    [anon_sym_is] = ACTIONS(9),
    [anon_sym_spawn] = ACTIONS(9),
    [anon_sym_supervised] = ACTIONS(9),
    [anon_sym_parallel] = ACTIONS(9),
    [anon_sym_detach] = ACTIONS(9),
    [anon_sym_blocking] = ACTIONS(9),
    [anon_sym_protocol] = ACTIONS(9),
    [anon_sym_interrupt] = ACTIONS(9),
    [anon_sym_forbid] = ACTIONS(9),
    [anon_sym_realtime] = ACTIONS(9),
    [anon_sym_defer] = ACTIONS(9),
    [anon_sym_errdefer] = ACTIONS(9),
    [anon_sym_select] = ACTIONS(9),
    [anon_sym_lemma] = ACTIONS(9),
    [sym_number_literal] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_comment] = ACTIONS(5),
    [sym_block_comment] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym__top_level] = STATE(3),
    [sym__declaration_placeholder] = STATE(3),
    [sym_string_literal] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_module] = ACTIONS(9),
    [anon_sym_import] = ACTIONS(9),
    [anon_sym_use] = ACTIONS(9),
    [anon_sym_export] = ACTIONS(9),
    [anon_sym_external] = ACTIONS(9),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_type] = ACTIONS(9),
    [anon_sym_effect] = ACTIONS(9),
    [anon_sym_alias] = ACTIONS(9),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_const] = ACTIONS(9),
    [anon_sym_mut] = ACTIONS(9),
    [anon_sym_consume] = ACTIONS(9),
    [anon_sym_readonly] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_else] = ACTIONS(9),
    [anon_sym_match] = ACTIONS(9),
    [anon_sym_for] = ACTIONS(11),
    [anon_sym_while] = ACTIONS(9),
    [anon_sym_loop] = ACTIONS(9),
    [anon_sym_in] = ACTIONS(11),
    [anon_sym_return] = ACTIONS(9),
    [anon_sym_break] = ACTIONS(9),
    [anon_sym_continue] = ACTIONS(9),
    [anon_sym_test] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [anon_sym_with] = ACTIONS(9),
    [anon_sym_throw] = ACTIONS(9),
    [anon_sym_as] = ACTIONS(9),
    [anon_sym_is] = ACTIONS(9),
    [anon_sym_spawn] = ACTIONS(9),
    [anon_sym_supervised] = ACTIONS(9),
    [anon_sym_parallel] = ACTIONS(9),
    [anon_sym_detach] = ACTIONS(9),
    [anon_sym_blocking] = ACTIONS(9),
    [anon_sym_protocol] = ACTIONS(9),
    [anon_sym_interrupt] = ACTIONS(9),
    [anon_sym_forbid] = ACTIONS(9),
    [anon_sym_realtime] = ACTIONS(9),
    [anon_sym_defer] = ACTIONS(9),
    [anon_sym_errdefer] = ACTIONS(9),
    [anon_sym_select] = ACTIONS(9),
    [anon_sym_lemma] = ACTIONS(9),
    [sym_number_literal] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_comment] = ACTIONS(5),
    [sym_block_comment] = ACTIONS(5),
  },
  [STATE(3)] = {
    [sym__top_level] = STATE(3),
    [sym__declaration_placeholder] = STATE(3),
    [sym_string_literal] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_module] = ACTIONS(23),
    [anon_sym_import] = ACTIONS(23),
    [anon_sym_use] = ACTIONS(23),
    [anon_sym_export] = ACTIONS(23),
    [anon_sym_external] = ACTIONS(23),
    [anon_sym_fn] = ACTIONS(23),
    [anon_sym_type] = ACTIONS(23),
    [anon_sym_effect] = ACTIONS(23),
    [anon_sym_alias] = ACTIONS(23),
    [anon_sym_let] = ACTIONS(23),
    [anon_sym_const] = ACTIONS(23),
    [anon_sym_mut] = ACTIONS(23),
    [anon_sym_consume] = ACTIONS(23),
    [anon_sym_readonly] = ACTIONS(23),
    [anon_sym_if] = ACTIONS(23),
    [anon_sym_else] = ACTIONS(23),
    [anon_sym_match] = ACTIONS(23),
    [anon_sym_for] = ACTIONS(26),
    [anon_sym_while] = ACTIONS(23),
    [anon_sym_loop] = ACTIONS(23),
    [anon_sym_in] = ACTIONS(26),
    [anon_sym_return] = ACTIONS(23),
    [anon_sym_break] = ACTIONS(23),
    [anon_sym_continue] = ACTIONS(23),
    [anon_sym_test] = ACTIONS(23),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_with] = ACTIONS(23),
    [anon_sym_throw] = ACTIONS(23),
    [anon_sym_as] = ACTIONS(23),
    [anon_sym_is] = ACTIONS(23),
    [anon_sym_spawn] = ACTIONS(23),
    [anon_sym_supervised] = ACTIONS(23),
    [anon_sym_parallel] = ACTIONS(23),
    [anon_sym_detach] = ACTIONS(23),
    [anon_sym_blocking] = ACTIONS(23),
    [anon_sym_protocol] = ACTIONS(23),
    [anon_sym_interrupt] = ACTIONS(23),
    [anon_sym_forbid] = ACTIONS(23),
    [anon_sym_realtime] = ACTIONS(23),
    [anon_sym_defer] = ACTIONS(23),
    [anon_sym_errdefer] = ACTIONS(23),
    [anon_sym_select] = ACTIONS(23),
    [anon_sym_lemma] = ACTIONS(23),
    [sym_number_literal] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(32),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_comment] = ACTIONS(5),
    [sym_block_comment] = ACTIONS(5),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym_identifier] = ACTIONS(37),
    [anon_sym_module] = ACTIONS(39),
    [anon_sym_import] = ACTIONS(39),
    [anon_sym_use] = ACTIONS(39),
    [anon_sym_export] = ACTIONS(39),
    [anon_sym_external] = ACTIONS(39),
    [anon_sym_fn] = ACTIONS(39),
    [anon_sym_type] = ACTIONS(39),
    [anon_sym_effect] = ACTIONS(39),
    [anon_sym_alias] = ACTIONS(39),
    [anon_sym_let] = ACTIONS(39),
    [anon_sym_const] = ACTIONS(39),
    [anon_sym_mut] = ACTIONS(39),
    [anon_sym_consume] = ACTIONS(39),
    [anon_sym_readonly] = ACTIONS(39),
    [anon_sym_if] = ACTIONS(39),
    [anon_sym_else] = ACTIONS(39),
    [anon_sym_match] = ACTIONS(39),
    [anon_sym_for] = ACTIONS(39),
    [anon_sym_while] = ACTIONS(39),
    [anon_sym_loop] = ACTIONS(39),
    [anon_sym_in] = ACTIONS(39),
    [anon_sym_return] = ACTIONS(39),
    [anon_sym_break] = ACTIONS(39),
    [anon_sym_continue] = ACTIONS(39),
    [anon_sym_test] = ACTIONS(39),
    [anon_sym_true] = ACTIONS(39),
    [anon_sym_false] = ACTIONS(39),
    [anon_sym_with] = ACTIONS(39),
    [anon_sym_throw] = ACTIONS(39),
    [anon_sym_as] = ACTIONS(39),
    [anon_sym_is] = ACTIONS(39),
    [anon_sym_spawn] = ACTIONS(39),
    [anon_sym_supervised] = ACTIONS(39),
    [anon_sym_parallel] = ACTIONS(39),
    [anon_sym_detach] = ACTIONS(39),
    [anon_sym_blocking] = ACTIONS(39),
    [anon_sym_protocol] = ACTIONS(39),
    [anon_sym_interrupt] = ACTIONS(39),
    [anon_sym_forbid] = ACTIONS(39),
    [anon_sym_realtime] = ACTIONS(39),
    [anon_sym_defer] = ACTIONS(39),
    [anon_sym_errdefer] = ACTIONS(39),
    [anon_sym_select] = ACTIONS(39),
    [anon_sym_lemma] = ACTIONS(39),
    [sym_number_literal] = ACTIONS(35),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_comment] = ACTIONS(5),
    [sym_block_comment] = ACTIONS(5),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(41),
    [anon_sym_module] = ACTIONS(41),
    [anon_sym_import] = ACTIONS(41),
    [anon_sym_use] = ACTIONS(41),
    [anon_sym_export] = ACTIONS(41),
    [anon_sym_external] = ACTIONS(41),
    [anon_sym_fn] = ACTIONS(41),
    [anon_sym_type] = ACTIONS(41),
    [anon_sym_effect] = ACTIONS(41),
    [anon_sym_alias] = ACTIONS(41),
    [anon_sym_let] = ACTIONS(41),
    [anon_sym_const] = ACTIONS(41),
    [anon_sym_mut] = ACTIONS(41),
    [anon_sym_consume] = ACTIONS(41),
    [anon_sym_readonly] = ACTIONS(41),
    [anon_sym_if] = ACTIONS(41),
    [anon_sym_else] = ACTIONS(41),
    [anon_sym_match] = ACTIONS(41),
    [anon_sym_for] = ACTIONS(43),
    [anon_sym_while] = ACTIONS(41),
    [anon_sym_loop] = ACTIONS(41),
    [anon_sym_in] = ACTIONS(43),
    [anon_sym_return] = ACTIONS(41),
    [anon_sym_break] = ACTIONS(41),
    [anon_sym_continue] = ACTIONS(41),
    [anon_sym_test] = ACTIONS(41),
    [anon_sym_true] = ACTIONS(41),
    [anon_sym_false] = ACTIONS(41),
    [anon_sym_with] = ACTIONS(41),
    [anon_sym_throw] = ACTIONS(41),
    [anon_sym_as] = ACTIONS(41),
    [anon_sym_is] = ACTIONS(41),
    [anon_sym_spawn] = ACTIONS(41),
    [anon_sym_supervised] = ACTIONS(41),
    [anon_sym_parallel] = ACTIONS(41),
    [anon_sym_detach] = ACTIONS(41),
    [anon_sym_blocking] = ACTIONS(41),
    [anon_sym_protocol] = ACTIONS(41),
    [anon_sym_interrupt] = ACTIONS(41),
    [anon_sym_forbid] = ACTIONS(41),
    [anon_sym_realtime] = ACTIONS(41),
    [anon_sym_defer] = ACTIONS(41),
    [anon_sym_errdefer] = ACTIONS(41),
    [anon_sym_select] = ACTIONS(41),
    [anon_sym_lemma] = ACTIONS(41),
    [sym_number_literal] = ACTIONS(41),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_comment] = ACTIONS(5),
    [sym_block_comment] = ACTIONS(5),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(45),
    [anon_sym_module] = ACTIONS(45),
    [anon_sym_import] = ACTIONS(45),
    [anon_sym_use] = ACTIONS(45),
    [anon_sym_export] = ACTIONS(45),
    [anon_sym_external] = ACTIONS(45),
    [anon_sym_fn] = ACTIONS(45),
    [anon_sym_type] = ACTIONS(45),
    [anon_sym_effect] = ACTIONS(45),
    [anon_sym_alias] = ACTIONS(45),
    [anon_sym_let] = ACTIONS(45),
    [anon_sym_const] = ACTIONS(45),
    [anon_sym_mut] = ACTIONS(45),
    [anon_sym_consume] = ACTIONS(45),
    [anon_sym_readonly] = ACTIONS(45),
    [anon_sym_if] = ACTIONS(45),
    [anon_sym_else] = ACTIONS(45),
    [anon_sym_match] = ACTIONS(45),
    [anon_sym_for] = ACTIONS(47),
    [anon_sym_while] = ACTIONS(45),
    [anon_sym_loop] = ACTIONS(45),
    [anon_sym_in] = ACTIONS(47),
    [anon_sym_return] = ACTIONS(45),
    [anon_sym_break] = ACTIONS(45),
    [anon_sym_continue] = ACTIONS(45),
    [anon_sym_test] = ACTIONS(45),
    [anon_sym_true] = ACTIONS(45),
    [anon_sym_false] = ACTIONS(45),
    [anon_sym_with] = ACTIONS(45),
    [anon_sym_throw] = ACTIONS(45),
    [anon_sym_as] = ACTIONS(45),
    [anon_sym_is] = ACTIONS(45),
    [anon_sym_spawn] = ACTIONS(45),
    [anon_sym_supervised] = ACTIONS(45),
    [anon_sym_parallel] = ACTIONS(45),
    [anon_sym_detach] = ACTIONS(45),
    [anon_sym_blocking] = ACTIONS(45),
    [anon_sym_protocol] = ACTIONS(45),
    [anon_sym_interrupt] = ACTIONS(45),
    [anon_sym_forbid] = ACTIONS(45),
    [anon_sym_realtime] = ACTIONS(45),
    [anon_sym_defer] = ACTIONS(45),
    [anon_sym_errdefer] = ACTIONS(45),
    [anon_sym_select] = ACTIONS(45),
    [anon_sym_lemma] = ACTIONS(45),
    [sym_number_literal] = ACTIONS(45),
    [anon_sym_DQUOTE] = ACTIONS(45),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_comment] = ACTIONS(5),
    [sym_block_comment] = ACTIONS(5),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(49),
    [anon_sym_module] = ACTIONS(49),
    [anon_sym_import] = ACTIONS(49),
    [anon_sym_use] = ACTIONS(49),
    [anon_sym_export] = ACTIONS(49),
    [anon_sym_external] = ACTIONS(49),
    [anon_sym_fn] = ACTIONS(49),
    [anon_sym_type] = ACTIONS(49),
    [anon_sym_effect] = ACTIONS(49),
    [anon_sym_alias] = ACTIONS(49),
    [anon_sym_let] = ACTIONS(49),
    [anon_sym_const] = ACTIONS(49),
    [anon_sym_mut] = ACTIONS(49),
    [anon_sym_consume] = ACTIONS(49),
    [anon_sym_readonly] = ACTIONS(49),
    [anon_sym_if] = ACTIONS(49),
    [anon_sym_else] = ACTIONS(49),
    [anon_sym_match] = ACTIONS(49),
    [anon_sym_for] = ACTIONS(51),
    [anon_sym_while] = ACTIONS(49),
    [anon_sym_loop] = ACTIONS(49),
    [anon_sym_in] = ACTIONS(51),
    [anon_sym_return] = ACTIONS(49),
    [anon_sym_break] = ACTIONS(49),
    [anon_sym_continue] = ACTIONS(49),
    [anon_sym_test] = ACTIONS(49),
    [anon_sym_true] = ACTIONS(49),
    [anon_sym_false] = ACTIONS(49),
    [anon_sym_with] = ACTIONS(49),
    [anon_sym_throw] = ACTIONS(49),
    [anon_sym_as] = ACTIONS(49),
    [anon_sym_is] = ACTIONS(49),
    [anon_sym_spawn] = ACTIONS(49),
    [anon_sym_supervised] = ACTIONS(49),
    [anon_sym_parallel] = ACTIONS(49),
    [anon_sym_detach] = ACTIONS(49),
    [anon_sym_blocking] = ACTIONS(49),
    [anon_sym_protocol] = ACTIONS(49),
    [anon_sym_interrupt] = ACTIONS(49),
    [anon_sym_forbid] = ACTIONS(49),
    [anon_sym_realtime] = ACTIONS(49),
    [anon_sym_defer] = ACTIONS(49),
    [anon_sym_errdefer] = ACTIONS(49),
    [anon_sym_select] = ACTIONS(49),
    [anon_sym_lemma] = ACTIONS(49),
    [sym_number_literal] = ACTIONS(49),
    [anon_sym_DQUOTE] = ACTIONS(49),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_comment] = ACTIONS(5),
    [sym_block_comment] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    ACTIONS(57), 1,
      anon_sym_DOLLAR_LBRACE,
    STATE(9), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(55), 2,
      aux_sym_string_literal_token1,
      aux_sym_string_literal_token2,
    ACTIONS(3), 3,
      sym_line_comment,
      sym_doc_comment,
      sym_block_comment,
  [19] = 5,
    ACTIONS(57), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(59), 1,
      anon_sym_DQUOTE,
    STATE(10), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(61), 2,
      aux_sym_string_literal_token1,
      aux_sym_string_literal_token2,
    ACTIONS(3), 3,
      sym_line_comment,
      sym_doc_comment,
      sym_block_comment,
  [38] = 5,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(68), 1,
      anon_sym_DOLLAR_LBRACE,
    STATE(10), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(65), 2,
      aux_sym_string_literal_token1,
      aux_sym_string_literal_token2,
    ACTIONS(3), 3,
      sym_line_comment,
      sym_doc_comment,
      sym_block_comment,
  [57] = 2,
    ACTIONS(3), 3,
      sym_line_comment,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(71), 4,
      anon_sym_DQUOTE,
      aux_sym_string_literal_token1,
      aux_sym_string_literal_token2,
      anon_sym_DOLLAR_LBRACE,
  [69] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [80] = 2,
    ACTIONS(75), 1,
      aux_sym_string_literal_token3,
    ACTIONS(3), 3,
      sym_line_comment,
      sym_doc_comment,
      sym_block_comment,
  [89] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(77), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 19,
  [SMALL_STATE(10)] = 38,
  [SMALL_STATE(11)] = 57,
  [SMALL_STATE(12)] = 69,
  [SMALL_STATE(13)] = 80,
  [SMALL_STATE(14)] = 89,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__declaration_placeholder, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__declaration_placeholder, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__declaration_placeholder, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__declaration_placeholder, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_nova(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
